insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '面食',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '点心',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '不辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '北方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '南方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,225, '海鲜',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,226, '是',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (87,226, '否',0);
update `jwb_goods` set goods_type=19 where goods_id=87;
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '面食',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '点心',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '不辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '北方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '南方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,225, '海鲜',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,226, '是',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (86,226, '否',0);
update `jwb_goods` set goods_type=19 where goods_id=86;
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '面食',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '点心',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '不辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '北方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '南方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,225, '海鲜',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,226, '是',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (85,226, '否',0);
update `jwb_goods` set goods_type=19 where goods_id=85;
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '面食',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '点心',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '不辣',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '北方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '南方',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,225, '海鲜',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,226, '是',0);
insert into `jwb_goods_attr` (`goods_id`,`attr_id`,`attr_value`,`attr_price`) values (84,226, '否',0);
update `jwb_goods` set goods_type=19 where goods_id=84;
